// This config header contains hardcoded defines
// that are compatible with FreeRDP 2
#ifndef _CONFIG_H
#define _CONFIG_H

#define HAVE_LIBPTHREAD
#define HAVE_PNG_GET_IO_PTR
#ifdef _WIN32
  #define ENABLE_WINSOCK
#endif

//#define HAVE_FREERDP_CONVERT_GDI_ORDER_COLOR
//#define HAVE_FREERDP_COLOR_CONVERT_DRAWING_ORDER_COLOR_TO_GDI_COLOR
//#define HAVE_FREERDP_DISPLAY_UPDATE_SUPPORT
#define HAVE_FREERDP_GATEWAY_SUPPORT
#define HAVE_FREERDP_LOAD_BALANCER_SUPPORT
#define HAVE_FREERDP_EVENT_PUBSUB
#define HAVE_FREERDP_REGISTER_ADDIN_PROVIDER
#define HAVE_RDPSETTINGS_SENDPRECONNECTIONPDU
//#define HAVE_FREERDP_CHANNELS_GLOBAL_INIT
#define HAVE_RDPSETTINGS_AUDIOPLAYBACK
#define HAVE_RDPSETTINGS_DEVICEREDIRECTION
#define CHANNEL_ENTRY_POINTS_FREERDP
#define FREERDP_BITMAP_REQUIRES_ALIGNED_MALLOC
#define ENABLE_WINPR

#endif
